CREATE TABLE `real_estate_properties` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text,
	`name` text NOT NULL,
	`description` text,
	`type` text DEFAULT 'APPARTEMENT' NOT NULL,
	`category` text DEFAULT 'RESIDENCE_PRINCIPALE' NOT NULL,
	`address` text,
	`city` text,
	`zipcode` text,
	`surface` real DEFAULT 0 NOT NULL,
	`purchase_price` real DEFAULT 0 NOT NULL,
	`purchase_date` text,
	`notary_fees` real DEFAULT 0 NOT NULL,
	`renovation_costs` real DEFAULT 0 NOT NULL,
	`estimated_value` real DEFAULT 0 NOT NULL,
	`monthly_rent` real DEFAULT 0 NOT NULL,
	`condo_fees` real DEFAULT 0 NOT NULL,
	`property_tax` real DEFAULT 0 NOT NULL,
	`floor` integer,
	`total_floors` integer,
	`rooms` integer DEFAULT 1 NOT NULL,
	`bedrooms` integer DEFAULT 1 NOT NULL,
	`bathrooms` integer DEFAULT 1 NOT NULL,
	`garages` integer DEFAULT 0 NOT NULL,
	`parking_spots` integer DEFAULT 0 NOT NULL,
	`garden_surface` real DEFAULT 0 NOT NULL,
	`terrace_surface` real DEFAULT 0 NOT NULL,
	`has_elevator` integer DEFAULT false NOT NULL,
	`is_new` integer DEFAULT false NOT NULL,
	`is_furnished` integer DEFAULT false NOT NULL,
	`kitchen_quality` text,
	`kitchen_condition` text,
	`bathroom_quality` text,
	`bathroom_condition` text,
	`flooring_quality` text,
	`flooring_condition` text,
	`windows_quality` text,
	`windows_condition` text,
	`general_quality` text,
	`general_condition` text,
	`ownership_pct` real DEFAULT 100 NOT NULL,
	`co_owners` text,
	`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `auth_user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `real_estate_user_idx` ON `real_estate_properties` (`user_id`);--> statement-breakpoint
ALTER TABLE `loans` ADD `property_id` integer REFERENCES real_estate_properties(id);--> statement-breakpoint
CREATE INDEX `loans_property_idx` ON `loans` (`property_id`);